name: .NET 10 Windows Service CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  ACTIONS_NODE_JS_FORCED_VERSION: 'node24'
  NODE_NO_WARNINGS: 1

jobs:
  build-and-publish:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x', '10.0.x']

    steps:
    - name: Checkout de código
      uses: actions/checkout@v4

    - name: Configurar .NET 10 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # 1. Restauramos ambos proyectos (la API y los Tests)
    # Al apuntar a la carpeta contenedora 'MyApp', .NET buscará todo lo que esté adentro
    - name: Restaurar Dependencias
      run: dotnet restore MyApp/

    # 2. Compilamos toda la solución/proyectos dentro de MyApp
    - name: Compilar Proyecto
      run: dotnet build MyApp/ --no-restore 

    # 3. EJECUTAMOS LAS PRUEBAS apuntando al proyecto de tests real
    - name: Ejecutar Pruebas
      run: dotnet test MyApp/"Xunit Moq"/"Xunit Moq.csproj" --no-build

